# Generated by Django 5.2.11 on 2026-03-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('rowCount', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AsplayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutID', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(max_length=20)),
                ('startTime', models.TimeField()),
                ('durationSeconds', models.DurationField()),
                ('playDate', models.DateField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dadreports.csvupload')),
            ],
            options={
                'indexes': [models.Index(fields=['playDate'], name='dadreports__playDat_f2a5f3_idx'), models.Index(fields=['artist'], name='dadreports__artist_f294cd_idx'), models.Index(fields=['cutID'], name='dadreports__cutID_6ab6c4_idx')],
            },
        ),
    ]
