# Generated by Django 5.2.11 on 2026-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(choices=[('vinyl', 'Vinyl'), ('cd', 'CD'), ('cassette', 'Cassette'), ('hard drive', 'Hard Drive'), ('other', 'Other')], max_length=10)),
                ('weglSticker', models.IntegerField(blank=True)),
            ],
        ),
    ]
