# Generated by Django 5.2.11 on 2026-04-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicalmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarecord',
            name='medium',
            field=models.CharField(choices=[('Vinyl', 'Vinyl'), ('CD', 'CD'), ('Cassette', 'Cassette'), ('Hard Drive', 'Hard Drive'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediarecord',
            name='weglSticker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
