# Generated by Django 6.0.2 on 2026-03-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djName', models.CharField(max_length=200)),
                ('absenceCount', models.IntegerField(default=0)),
            ],
        ),
    ]
