# Generated by Django 6.0.3 on 2026-04-06 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnAirShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('joinDate', models.DateField(verbose_name='date dj joined wegl')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dj_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenceCount', models.IntegerField(default=0)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='djrecord.dj')),
            ],
        ),
        migrations.CreateModel(
            name='OnAirShowDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djrecord.dj')),
                ('onairshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djrecord.onairshow')),
            ],
            options={
                'unique_together': {('onairshow', 'dj')},
            },
        ),
        migrations.AddField(
            model_name='onairshow',
            name='djs',
            field=models.ManyToManyField(blank=True, related_name='shows', through='djrecord.OnAirShowDJ', to='djrecord.dj'),
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('startTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='djrecord.onairshow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('show', 'day', 'startTime'), name='uniqueShowTimeslot')],
            },
        ),
    ]
