# Generated by Django 5.2.11 on 2026-02-18 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('joinDate', models.DateField(verbose_name='date dj joined wegl')),
            ],
        ),
        migrations.CreateModel(
            name='OnAirShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('djs', models.ManyToManyField(blank=True, related_name='shows', to='djrecord.dj')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('startTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='djrecord.onairshow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('show', 'day', 'startTime'), name='uniqueShowTimeslot')],
            },
        ),
    ]
