# Generated by Django 5.2.11 on 2026-04-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onairshowdj',
            table='djrecord_onairshow_djs',
        ),
    ]
