# Generated by Django 6.0.2 on 2026-03-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrecord', '0002_remove_onairshow_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='onairshow',
            name='showTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
