# Generated by Django 6.0.2 on 2026-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrecord', '0003_onairshow_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onairshow',
            name='showTime',
        ),
        migrations.AddField(
            model_name='onairshow',
            name='day',
            field=models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True),
        ),
        migrations.AddField(
            model_name='onairshow',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
