# Generated by Django 6.0.2 on 2026-04-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrecord', '0004_remove_onairshow_showtime_onairshow_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenceCount', models.IntegerField(default=0)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='djrecord.dj')),
            ],
        ),
    ]
